# Generated by Django 6.0.5 on 2026-05-19 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('gestor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academia_gerenciada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academia',
                'verbose_name_plural': 'Academias',
            },
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('LIBERADO', 'Liberado'), ('NEGADO', 'Negado'), ('DESCONHECIDO', 'Desconhecido')], default='DESCONHECIDO', max_length=12)),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='core.academia')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlunoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Aluno',
                'verbose_name_plural': 'Perfis dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('max_checkins_dia', models.PositiveIntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.academia')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.academia')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='core.plano')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'academia')},
            },
        ),
    ]
