# Generated by Django 6.0.5 on 2026-05-19 17:54

from django.db import migrations


PERMISSOES_GESTORES = [
    ('core', 'academia', 'view_academia'),
    ('core', 'plano', 'add_plano'),
    ('core', 'plano', 'change_plano'),
    ('core', 'plano', 'delete_plano'),
    ('core', 'plano', 'view_plano'),
    ('core', 'matricula', 'add_matricula'),
    ('core', 'matricula', 'change_matricula'),
    ('core', 'matricula', 'delete_matricula'),
    ('core', 'matricula', 'view_matricula'),
    ('core', 'acesso', 'view_acesso'),
    ('core', 'alunoperfil', 'add_alunoperfil'),
    ('core', 'alunoperfil', 'change_alunoperfil'),
    ('core', 'alunoperfil', 'view_alunoperfil'),
    ('auth', 'user', 'add_user'),
    ('auth', 'user', 'change_user'),
    ('auth', 'user', 'view_user'),
]


def criar_grupo_gestores(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    grupo, _ = Group.objects.get_or_create(name='Gestores')

    permissoes = []
    for app_label, model, codename in PERMISSOES_GESTORES:
        ct, _ = ContentType.objects.get_or_create(app_label=app_label, model=model)
        perm, _ = Permission.objects.get_or_create(
            content_type=ct,
            codename=codename,
            defaults={'name': codename},
        )
        permissoes.append(perm)

    grupo.permissions.set(permissoes)


def remover_grupo_gestores(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Gestores').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(criar_grupo_gestores, remover_grupo_gestores),
    ]
