# Generated by Django 6.0.5 on 2026-05-20 01:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_criar_grupo_gestores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='max_checkins_dia',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='plano',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
